#include "centerpoint_msgs/msg/Bbox.idl"
#include "std_msgs/msg/Header.idl"

module centerpoint_msgs {
  module msg {
    struct LaneArray {
      std_msgs::msg::Header header;       
      sequence<centerpoint_msgs::msg::LanePointArray> lanes;
    };
  };   
};
